name: github clone and update
description: github clone and update
author: yyj
branding:
  icon: download
  color: blue




runs:
  using: composite
  steps:
    - name: checkout project code
      id: cpc
      run: |
        GITREPO_NAME=${{ github.repository }}
        prj_name=${GITREPO_NAME#*/}
        echo "prj_name=${prj_name}" 
        if [ -z "$(ls -A ./|grep -v .git)" ]
        then
          cd ..
          rm -rf ${prj_name}
          git clone git@github.com:${{ github.repository }}
          cd -
          git checkout ${{ github.ref_name }}
        else
          git pull
          git checkout ${{ github.ref_name }}
        fi
      shell: bash
