name: github clone
description: github clone
author: yyj


inputs:
  branch:
    description: branch
    default: ${{ github.ref_name }}


runs:
  using: composite
  steps:
    - name: pull
      run: |
        GITREPO_NAME=${{ github.repository }}
        project_name=${GITREPO_NAME#*/}
        if [ -z "$(ls -A ./|grep -v .git)" ]
        then
          cd .. && rm -rf ${project_name}
          git clone git@github.com:${{ github.repository }}
          cd -
        else
          git pull
        fi
      shell: bash

    - name: checkout
      run: git checkout ${{ inputs.branch }}
      shell: bash

